#!/usr/bin/env python3

import os
import sqlite3
import shutil
import tempfile
import requests
from datetime import datetime

# ── Config ────────────────────────────────────────────────────────────────────

CHROME_PROFILE = "Profile 21"
CHROME_BASE    = os.path.expanduser(f"~/.config/google-chrome/{CHROME_PROFILE}")
# BACKEND_URL    = "https://videosaver.online/internal/cookies"
BACKEND_URL    = "http://localhost:8080/internal/cookies"
API_KEY        = "buckty-internal-secret"
OUTPUT_FILE    = "cookies.txt"

# Platform → domains to extract
PLATFORMS = {
    "YouTube":     [".youtube.com", "youtube.com"],
    "Instagram":   [".instagram.com", "instagram.com"],
    "Twitter":     [".twitter.com", "twitter.com", ".x.com", "x.com"],
    "TikTok":      [".tiktok.com", "tiktok.com"],
    "Facebook":    [".facebook.com", "facebook.com"],
    "Dailymotion": [".dailymotion.com", "dailymotion.com"],
    "LinkedIn":    [".linkedin.com", "linkedin.com"],
    "Reddit":      [".reddit.com", "reddit.com"],
}

# ── Cookie extraction ─────────────────────────────────────────────────────────

def extract_cookies_from_chrome(domains: list[str]) -> list[dict]:
    cookies_db = os.path.join(CHROME_BASE, "Network", "Cookies")
    if not os.path.exists(cookies_db):
        cookies_db = os.path.join(CHROME_BASE, "Cookies")

    if not os.path.exists(cookies_db):
        print(f"[!] Cookies DB not found at {cookies_db}")
        return []

    # Copy DB to temp — Chrome locks the original
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".db")
    shutil.copy2(cookies_db, tmp.name)
    tmp.close()

    cookies = []
    try:
        conn = sqlite3.connect(tmp.name)
        cursor = conn.cursor()

        placeholders = ",".join(["?" for _ in domains])
        query = f"""
            SELECT host_key, name, value, path, expires_utc, is_secure, is_httponly
            FROM cookies
            WHERE host_key IN ({placeholders})
            ORDER BY host_key, name
        """
        cursor.execute(query, domains)
        rows = cursor.fetchall()
        conn.close()

        for row in rows:
            host_key, name, value, path, expires_utc, is_secure, is_httponly = row
            # Chrome stores expiry as microseconds since 1601-01-01
            # Convert to Unix timestamp
            if expires_utc > 0:
                unix_expires = (expires_utc - 11644473600000000) // 1000000
            else:
                unix_expires = 0

            cookies.append({
                "host":       host_key,
                "subdomains": "TRUE" if host_key.startswith(".") else "FALSE",
                "path":       path,
                "secure":     "TRUE" if is_secure else "FALSE",
                "expires":    unix_expires,
                "name":       name,
                "value":      value,
                "httponly":   bool(is_httponly),
            })
    except Exception as e:
        print(f"[!] DB read error: {e}")
    finally:
        os.unlink(tmp.name)

    return cookies

# ── Netscape format ───────────────────────────────────────────────────────────

def to_netscape_line(cookie: dict) -> str:
    prefix = "#HttpOnly_" if cookie["httponly"] else ""
    return (
        f"{prefix}{cookie['host']}\t"
        f"{cookie['subdomains']}\t"
        f"{cookie['path']}\t"
        f"{cookie['secure']}\t"
        f"{cookie['expires']}\t"
        f"{cookie['name']}\t"
        f"{cookie['value']}"
    )

def build_netscape_file(all_cookies: dict[str, list[dict]]) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Buckty cookie extractor",
        f"# Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC",
        "",
    ]

    for platform, cookies in all_cookies.items():
        if not cookies:
            continue
        lines.append(f"# ── {platform} ({'─' * (40 - len(platform))})")
        for cookie in cookies:
            lines.append(to_netscape_line(cookie))
        lines.append("")

    return "\n".join(lines)

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print(f"[*] Extracting cookies from Chrome profile: {CHROME_PROFILE}")
    print()

    all_cookies = {}
    total = 0

    for platform, domains in PLATFORMS.items():
        cookies = extract_cookies_from_chrome(domains)
        all_cookies[platform] = cookies
        total += len(cookies)
        status = f"{len(cookies)} cookies" if cookies else "none found"
        print(f"  [{platform}] {status}")

    print()
    print(f"[*] Total cookies extracted: {total}")

    if total == 0:
        print("[!] No cookies found — make sure you are logged in on all platforms in Chrome Profile 21")
        return

    netscape_content = build_netscape_file(all_cookies)

    # Save locally
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(netscape_content)
    print(f"[*] Saved locally → {OUTPUT_FILE}")

    # POST to backend
    print(f"[*] Uploading to {BACKEND_URL} ...")
    try:
        resp = requests.post(
            BACKEND_URL,
            data=netscape_content.encode("utf-8"),
            headers={
                "X-Internal-Key": API_KEY,
                "Content-Type":   "text/plain",
            },
            timeout=15,
        )
        if resp.status_code == 200:
            print("[✔] Cookies uploaded successfully")
        else:
            print(f"[!] Upload failed — HTTP {resp.status_code}: {resp.text}")
    except Exception as e:
        print(f"[!] Upload error: {e}")
        print(f"[*] Cookies saved locally at {OUTPUT_FILE} — upload manually if needed")

if __name__ == "__main__":
    main()